// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3pIaZkqOWR39QJVdXgb18r4m4XioCpj4',
    appId: '1:991135427917:web:7635579590d941850a1b04',
    messagingSenderId: '991135427917',
    projectId: 'get-strong-d799f',
    authDomain: 'get-strong-d799f.firebaseapp.com',
    storageBucket: 'get-strong-d799f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSmYJyxgvPT4HMgrgfirJHBuj3mpooznU',
    appId: '1:991135427917:android:4ce548937eac012d0a1b04',
    messagingSenderId: '991135427917',
    projectId: 'get-strong-d799f',
    storageBucket: 'get-strong-d799f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYRpVxSfzdaWDXglKjhRGnYjZnV03fltY',
    appId: '1:991135427917:ios:94a9306bbcb968770a1b04',
    messagingSenderId: '991135427917',
    projectId: 'get-strong-d799f',
    storageBucket: 'get-strong-d799f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYRpVxSfzdaWDXglKjhRGnYjZnV03fltY',
    appId: '1:991135427917:ios:94a9306bbcb968770a1b04',
    messagingSenderId: '991135427917',
    projectId: 'get-strong-d799f',
    storageBucket: 'get-strong-d799f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
